### ISSUE TITLE
Your scss folder is missing its components

### ISSUE THREAD

**Issue by SimonPadbury** [zurb/foundation-compass-template#9]
Did you know there are no component folders within the `scss/` folder?

I'm just starting a project and I had to copy these from your bower repo.

**Comment by gakimball** [comment]
This is intentional, because the Sass files are considered source files and aren't meant to be modified. This template automatically sets `bower_components/foundation/scss` as an available import path.

To be sure, there's nothing wrong with modifying the source files directly, but we expect the majority of users to just import them.
